server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/myschool?serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=utf8
#    username: root
#    password: ckl010203
#  devtools:
#    restart:
#      enabled: true
mybatis:
  type-aliases-package: com.lime.entity
  mapper-locations: classpath:mapper/*.xml