server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/myschool?serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=utf8
#    username: root
#    password: ckl010203
#  devtools:
#    restart:
#      enabled: true
spring:
  redis:
    host: 192.168.80.129
    port: 6379
    password: lime
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
mybatis:
  type-aliases-package: com.lime.entity
  mapper-locations: classpath:mapper/*.xml